name = "multimodal-vision-ocr-worker"
main = "index.js"
compatibility_date = "2024-11-07"

# This binding exposes the AI model service to your Worker under the name 'AI'
[ai]
binding = "AI"

# Environment variable to store the allowed origin (your Cloudflare Pages URL)
[vars]
ALLOWED_ORIGIN = "https://www.claranueva.com/" # REPLACE with http://localhost:8080" for developing locally and with https://www.claranueva.com/ with your actual Pages domain or "https://yourdomain.com" if using a custom domain